[cms]
ai.hse.akhcheck.ru

[cms:vars]
ansible_user=ai2026-hse-092
ansible_python_interpreter=/usr/bin/python3
# Аутентификация: либо --ask-pass, либо настройте SSH-ключ:
#   ssh-copy-id ai2026-hse-092@ai.hse.akhcheck.ru
